### ISSUE TITLE
CrashConfigModMenu4.0.0Alpha.5

### ISSUE THREAD

**Issue by bi95** [EnnuiL/OkZoomer#9]
Crash when open Config UI  with Optifine
version:4.0.0Alpha.5
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 8/9/20 7:28 AM
Description: Rendering screen

java.lang.IllegalAccessError: tried to access method net.minecraft.class_327.method_1724(Ljava/lang/String;FFIZLnet/minecraft/class_1159;Lnet/minecraft/class_4597;ZII)F from class me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen
	at me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen.method_25394(GlobalizedClothConfigScreen.java:252)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by EnnuiL** [comment]
This issue has been probably fixed on one of the 4.0.0 betas, and now, we don't use Cloth Config anymore, closing
